apiVersion: v1
kind: Pod
metadata:
  name: node-affintiy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node
              operator: In
              values:
                - controlplane
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: node
      operation: "Exists"
      effect: "NoSchedule"