apiVersion: v1
kind: Pod
metadata:
  name: node-affintiy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node
              operator: In
              values:
                - controlplane
                  node01
  containers:
    - name: nginx
      image: nginx
  # With affinity we can also use the taints and tolerations to schedule the pods
  tolerations:
    # - key: node
    #   operator: "Exists"
    #   effect: "NoSchedule"
