apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-with-preff
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: roboshop
                operator: In
                values:
                  - node-5
  containers:
    - name: nginx
      image: nginx