apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-with-preff
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node
                operator: In
                values:
                  - node01
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: roboshop
                operator: In
                values:
                  - node-3
  containers:
    - name: nginx
      image: nginx