apiVersion: v1
kind: Pod
metadata:
  name: node-affintiy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - key: env
            operator: In
            values:
              - dev
  containers:
    - name: nginx
      image: nginx