apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node
                operator: NotIn
                values:
                  - node-1
              - key: roboshop
                operator: NotIn
                values:
                  - node-2
              - key: roboshop
                operator: NotIn
                values:
                  - node-4
  containers:
    - name: nginx
      image: nginx