apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
  labels:
    project: roboshop
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              project: roboshop
  containers:
    - name: nginx
      image: nginx