apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tolerations
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: taints-n-tolerations
      labels:
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx
      # Here we have tainted a node with a key and value pair
      # adding the tolerations to this pod to be scheduled on that node with some parameters like key and values
      tolerations:
        - key: env
          operator: "Exists"
          effect: "NoSchedule"